#!/bin/bash

# Google Indexing Quick Submit Script
# สคริปต์สำหรับ submit URLs ไปยัง Google Search Console อย่างรวดเร็ว

echo "🚀 CoinZone - Google Indexing Quick Submit"
echo "=========================================="
echo ""

# URLs ที่ต้อง submit (เรียงตามความสำคัญ)
URLS=(
  "https://www.coin-zone.shop/"
  "https://www.coin-zone.shop/coinzone.html"
  "https://www.coin-zone.shop/รับเติมเกม.html"
  "https://www.coin-zone.shop/รับเติมเกม-seo.html"
  "https://www.coin-zone.shop/แอปพรีเมียม.html"
  "https://www.coin-zone.shop/game-topup"
  "https://www.coin-zone.shop/premium-app"
  "https://www.coin-zone.shop/card-topup"
  "https://www.coin-zone.shop/cash-card"
)

echo "📋 URLs ที่ต้อง submit ไปยัง Google Search Console:"
echo ""

for i in "${!URLS[@]}"; do
  echo "$((i+1)). ${URLS[$i]}"
done

echo ""
echo "=========================================="
echo "📝 ขั้นตอนการ Submit:"
echo ""
echo "1. เปิด Google Search Console:"
echo "   https://search.google.com/search-console"
echo ""
echo "2. เลือก Property: www.coin-zone.shop"
echo ""
echo "3. สำหรับแต่ละ URL ด้านบน:"
echo "   - ไปที่ URL Inspection (เมนูซ้าย)"
echo "   - Paste URL"
echo "   - กด Enter"
echo "   - รอ Google ตรวจสอบ (10-30 วินาที)"
echo "   - คลิก 'Request Indexing'"
echo "   - รอ 1-2 นาที"
echo "   - ทำต่อกับ URL ถัดไป"
echo ""
echo "4. Submit Sitemap:"
echo "   - ไปที่ Sitemaps (เมนูซ้าย)"
echo "   - Add new sitemap: sitemap.xml"
echo "   - คลิก Submit"
echo ""
echo "=========================================="
echo "🔍 ทดสอบว่าเว็บถูก Index หรือยัง:"
echo ""
echo "ใน Google Search พิมพ์:"
echo "  site:coin-zone.shop"
echo "  site:www.coin-zone.shop"
echo ""
echo "ถ้าขึ้นผลลัพธ์ = ถูก index แล้ว ✅"
echo "ถ้าไม่ขึ้น = ยังไม่ถูก index ❌"
echo ""
echo "=========================================="
echo "⏰ Timeline คาดการณ์:"
echo ""
echo "1-3 วัน     → site:coin-zone.shop เริ่มเจอ"
echo "3-7 วัน     → ค้นหา 'CoinZone' เจอ"
echo "1-2 สัปดาห์ → ค้นหา 'coinzone' เจอหน้าแรก"
echo "2-4 สัปดาห์ → Keywords อื่นๆ เริ่มขึ้น"
echo ""
echo "=========================================="
echo "✅ Checklist รายวัน:"
echo ""
echo "□ ทดสอบ site:coin-zone.shop"
echo "□ ทดสอบค้นหา 'CoinZone'"
echo "□ ทดสอบค้นหา 'coinzone'"
echo "□ ตรวจสอบ Google Search Console"
echo "□ แชร์ลิงค์ใน social media"
echo ""
echo "=========================================="
echo ""
echo "💡 Tips:"
echo "- อดทนรอ 1-2 สัปดาห์"
echo "- Submit URLs ทุกวันจนกว่าจะขึ้น"
echo "- แชร์ลิงค์ใน social media บ่อยๆ"
echo "- เพิ่มเนื้อหาใหม่เป็นประจำ"
echo ""
echo "🎯 เป้าหมาย: ให้เว็บขึ้นหน้าแรก Google เมื่อค้นหา 'CoinZone' และ 'coinzone'"
echo ""
